# -*- coding: utf-8 -*-
"""VD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163osb8WRzi8viOgPJxv5283PmBntEPv9
"""

import streamlit as st
import pandas as pd
import glob
import re
import os
import numpy as np
from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, log_loss
)
import altair as alt
import matplotlib.pyplot as plt

#Carga de datos ya procesados
df_leaderboard = pd.read_parquet('df_leaderboard.parquet')
df_testpredcv = pd.read_parquet('df_testpredcv.parquet')
df_feature_importance = pd.read_parquet('df_feature_importance.parquet')
df_metrics = pd.read_parquet('df_metrics.parquet')
st.markdown(
    """
    <style>
    .streamlit-expander > div, .css-1l02zno { 
        padding: 0 !important; 
        margin: 0 !important;
    }
    </style>
    <style>
        .css-xyz123 {
            background-color: #1f77b4 !important;  /* Azul */
        }
    </style>
    """, unsafe_allow_html=True
)
df = df_metrics

#Panel de filtros laterales
st.sidebar.title("Filtros")
nvariables_options = sorted(df['Nvariables'].unique())
nfolds_options = sorted(df['nFolds'].unique())
seed_options = sorted(df['Seed'].unique())

nvariables_filter = st.sidebar.multiselect(
    "Número de variables del modelo",
    options=nvariables_options,
    default=nvariables_options
)

nfolds_filter = st.sidebar.multiselect(
    "Filtrar por NFolds",
    options=nfolds_options,
    default=nfolds_options
)

seed_filter = st.sidebar.multiselect(
    "Filtrar por Seed",
    options=seed_options,
    default=seed_options
)

df_top = df[
    (df['Nvariables'].isin(nvariables_filter)) &
    (df['nFolds'].isin(nfolds_filter)) &
    (df['Seed'].isin(seed_filter))
]
roc_seed = df_top.groupby('Seed')['ROC_AUC'].mean().reset_index()
global_mean = roc_seed['ROC_AUC'].mean()
mean_df = pd.DataFrame({
    'Seed': roc_seed['Seed'],
    'ROC_AUC': [global_mean] * len(roc_seed)
})
base = alt.Chart(roc_seed).encode(
    x=alt.X('Seed:O', title='Seed'),
    y=alt.Y('ROC_AUC:Q', title='ROC AUC medio'),
    tooltip=['Seed', 'ROC_AUC']
)
bars = base.mark_bar().encode(
    color='Seed:N'
)
line = alt.Chart(mean_df).mark_line(color='black', strokeDash=[5,5]).encode(
    x='Seed:O',
    y='ROC_AUC:Q'
)
chart = (bars + line).properties(
    title='ROC AUC medio por Seed'
).interactive()
chart = chart.encode(
    y=alt.Y('ROC_AUC:Q', scale=alt.Scale(domain=[0.85, 0.94]))
)
st.title("Análisis de ROC AUC por Seed")
st.altair_chart(chart, use_container_width=True)

model_stats = df_top.groupby('Model').agg({
    'ROC_AUC': 'mean',
    'Precision_macro': 'mean',
    'Recall_macro': 'mean'
}).reset_index()

k = st.slider('Número de mejores modelos a mostrar', min_value=1, max_value=len(model_stats), value=5)
top_models = model_stats.nlargest(k, 'ROC_AUC')
model_options = top_models['Model']
selected_models = st.multiselect(
    'Selecciona los modelos a incluir',
    options=model_options,
    default=model_options.tolist()
)

filtered_df = df_top[df_top['Model'].isin(selected_models)]
model_means = filtered_df.groupby('Model').agg({
    'ROC_AUC': 'mean',
    'Precision_macro': 'mean',
    'Recall_macro': 'mean'
}).reset_index()

chart = alt.Chart(
    model_means
).mark_circle().encode(
    x=alt.X('Precision_macro', title='Precisión', scale=alt.Scale(domain=[0.7, 0.9])),
    y=alt.Y('Recall_macro', title='Recall', scale=alt.Scale(domain=[0.7, 0.9])),
    size=alt.Size('ROC_AUC', title='ROC_AUC', scale=alt.Scale(range=[400, 1000])),
    color=alt.Color('Model', legend=alt.Legend(title="Model")),
    tooltip=['Model','ROC_AUC','Precision_macro','Recall_macro']
).properties(
    width=400,
    height=600,
    title='Modelos con métricas medias: Precisión vs Recall, tamaño por ROC_AUC'
)
st.altair_chart(chart, use_container_width=True)

avg_by_vars = filtered_df.groupby('Nvariables').agg({'ROC_AUC': 'mean'}).reset_index()
avg_by_folds = filtered_df.groupby('nFolds').agg({'ROC_AUC': 'mean'}).reset_index()

chart_vars = alt.Chart(avg_by_vars).mark_bar().encode(
    y=alt.Y('Nvariables:N', title='Número de Variables'),
    x=alt.X('ROC_AUC:Q', title='Media ROC_AUC'),
    color=alt.Color('Nvariables:N', legend=alt.Legend(title='Variables'), 
                    scale=alt.Scale(scheme='set2')),
    tooltip=['Nvariables', 'ROC_AUC']
).properties(
    title='Media de ROC_AUC por Número de Variables'
)
st.altair_chart(chart_vars, use_container_width=True)

chart_folds = alt.Chart(avg_by_folds).mark_bar().encode(
    y=alt.Y('nFolds:N', title='Número de Folds'),
    x=alt.X('ROC_AUC:Q', title='Media ROC_AUC'),
    color=alt.Color('nFolds:N', legend=alt.Legend(title='Folds'), 
                    scale=alt.Scale(scheme='paired')),
    tooltip=['nFolds', 'ROC_AUC']
).properties(
    title='Media de ROC_AUC por Número de Folds'
)
st.altair_chart(chart_folds, use_container_width=True)

df_filtered = df_feature_importance[
    (df_feature_importance['Nvariables'].isin(nvariables_filter)) &
    (df_feature_importance['nFolds'].isin(nfolds_filter)) &
    (df_feature_importance['Seed'].isin(seed_filter)) &
    (df_feature_importance['Model'].isin(selected_models))
]
importance_media = df_filtered.groupby('feature').agg({
    'importance': 'mean'
}).reset_index()
importance_media = importance_media.sort_values(by='importance', ascending=False)

chart = alt.Chart(importance_media).mark_bar().encode(
    y=alt.Y('feature:N', sort='-x', title='Variables'),
    x=alt.X('importance:Q', title='Importancia media'),
    tooltip=['feature', 'importance']
).properties(
    width=700,
    height=importance_media.shape[0] * 25,
    title='Ranking de variables por importancia media'
)
st.altair_chart(chart, use_container_width=True)

df_leaderboard_filtered = df_leaderboard[
    (df_leaderboard['Nvariables'].isin(nvariables_filter)) &
    (df_leaderboard['nFolds'].isin(nfolds_filter)) &
    (df_leaderboard['Seed'].isin(seed_filter)) &
    (df_leaderboard['Model'].isin(selected_models))
]

df_grouped = df_leaderboard_filtered.groupby('Fold').agg({
    'ROC_AUC': 'mean',
    'Roc_auc_byFold': 'max'
}).reset_index()

df_grouped.columns = ['Fold', 'ROC_AUC_fold', 'ROC_AUC_modelo']
df_long = df_grouped.melt('Fold', var_name='Tipo', value_name='Valor')

bars = alt.Chart(df_long[df_long['Tipo'] == 'ROC_AUC_fold']).mark_bar().encode(
    x=alt.X('Fold:O', title='Fold'),
    y=alt.Y('Valor:Q', title='ROC_AUC_fold'),
    color=alt.Color('Fold:N', legend=None),
    tooltip=['Fold', 'Valor']
)

line = alt.Chart(df_long[df_long['Tipo'] == 'ROC_AUC_modelo']).mark_line(color='blue', size=2).encode(
    x='Fold:O',
    y='Valor:Q',
    tooltip=['Fold', 'Valor']
)

chart = (bars + line).properties(
    width=650,
    height=350,
    title='ROC_AUC por Fold frente al del modelo'
)
st.altair_chart(chart, use_container_width=True)

df_testpredcv_filtered = df_testpredcv[
    (df_testpredcv['Nvariables'].isin(nvariables_filter)) &
    (df_testpredcv['nFolds'].isin(nfolds_filter)) &
    (df_testpredcv['Seed'].isin(seed_filter)) &
    (df_testpredcv['Model'].isin(selected_models))
]
df_testpredcv_filtered['pred'] = (df_testpredcv_filtered['testPredProba'] >= 0.5).astype(int)
df_testpredcv_filtered['error'] = (df_testpredcv_filtered['pred'] != df_testpredcv_filtered['clasereal']).astype(int)
resumen = df_testpredcv_filtered.groupby(['etiq-id', 'clasereal']).agg(
    errores=('error', 'sum'),
    correctas=('error', lambda x: (x==0).sum())
).reset_index()
resumen['total'] = resumen['errores'] + resumen['correctas']
chart = alt.Chart(resumen).mark_circle().encode(
    x=alt.X('correctas:Q', title='Número de clasificaciones correctas'),
    y=alt.Y('errores:Q', title='Número de clasificaciones incorrectas'),
    size=alt.Size('errores:Q', title='Total de clasificaciones'),
    color=alt.Color('etiq-id', legend=alt.Legend(title="etiq-id")),
    tooltip=['etiq-id', 'clasereal', 'errores', 'correctas', 'total']
).properties(
    width=600,
    height=400,
    title='Errores vs Aciertos por muestra'
)
st.altair_chart(chart, use_container_width=True)